apiVersion: v1
kind: Secret
metadata:
  name: authdb-secret
  namespace: authdb
  labels:
    app.kubernetes.io/name: authdb
type: Opaque
stringData:
  SECRET_KEY: 7939816eef871f2c7b7a85f5a937ad1539959042a25f83c8693a2738301e1acd
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  MONGODB_ROOT_USER: admin
  MONGODB_ROOT_PASSWORD: admin_auth_db_123
  MONGODB_DB: auth_scaleDB
