apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: authdb
  labels:
    app.kubernetes.io/name: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: task-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: task-service
    spec:
      containers:
        - name: task-service
          image: 765951922643.dkr.ecr.ap-south-1.amazonaws.com/authdb/task-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
              name: http
          envFrom:
            - configMapRef:
                name: authdb-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: SECRET_KEY
            - name: TASK_SERVICE_PORT
              value: "8003"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: MONGODB_ROOT_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: MONGODB_ROOT_PASSWORD
            - name: MONGODB_DB
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: MONGODB_DB
            - name: MONGODB_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongodb:27017/$(MONGODB_DB)?authSource=admin
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672/
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
